replicaCount: 1

image:
  repository: belka75/movie-svc
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

env:
  LOG_LEVEL: "DEBUG" 

db:
  user: movie_user
  secretName: movie-db-postgresql
  name: movie_db

castServicePath: "/api/v1/casts/"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30 
