apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-init
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: postgres:12.1-alpine
        env:
        - name: PGHOST
          value: "movie-db-postgresql.{{ .Release.Namespace }}.svc"
        - name: PGUSER
          value: "{{ .Values.db.user }}"
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Values.db.secretName .Release.Namespace }}
              key: {{ .Values.db.secretKey }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            DB_NAME="{{ printf "%s%s" .Values.db.namePrefix .Release.Namespace }}"
            echo "Checking DB existence..."
            
            timeout 60s bash -c 'until pg_isready -h $PGHOST -U $PGUSER; do sleep 5; done' || {
              echo "Database not ready after 60s, skipping init"
              exit 0
            }

            EXISTS=$(psql -h $PGHOST -U $PGUSER -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'")
            if [ "$EXISTS" = "1" ]; then
              echo "DB $DB_NAME already exists, skipping init"
              exit 0
            fi

            echo "Creating DB $DB_NAME..."
            psql -h $PGHOST -U $PGUSER -d postgres -c "CREATE DATABASE $DB_NAME;"
