apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie.fullname" . }}
  labels:
    {{- include "movie.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "movie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "movie.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: "{{ .Values.db.secretName }}.{{ .Release.Namespace }}.svc.cluster.local"

            - name: DB_USER
              value: "{{ .Values.db.user }}"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
            
            - name: DATABASE_URI            
              value: "postgresql://{{ .Values.db.user }}:$(DB_PASSWORD)@{{ .Values.db.secretName }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.db.name }}"

            - name: CAST_SERVICE_HOST_URL
              value: "http://cast-svc.{{ .Release.Namespace }}.svc.cluster.local:8000/api/v1/casts/"

            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL | default "INFO" }}"

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
