replicaCount: 1

image:
  repository: belka75/cast-svc    
  tag: v2                        
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000                  

env:
  DB_HOST: "cast-db-postgresql.app-dev.svc.cluster.local"
  LOG_LEVEL: "DEBUG"

db:
  user: cast_user
  password: cast_password
  namePrefix: cast_db_
  secretName: cast-db-postgresql
  secretKey: connection-string


resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
