{{- $secretName := printf "%s-%s" .Values.db.secretName .Release.Namespace }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if not $existing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  connection-string: {{ printf "postgresql://%s:%s@%s-db-postgresql.%s.svc.cluster.local:5432/%s%s" .Values.db.user .Values.db.password .Chart.Name .Release.Namespace .Values.db.namePrefix .Release.Namespace | b64enc | quote }}
{{- end }}
